tasks:
  - name: copy_opatch
    description: "This task copies OPatch."
    execute: Y
    type: local
    path: /u01/home/oracle/OraPatch_Stage/PrePatch/copy_opatch.sh
    arguments: [OraHome, BkpLoc, OpatchZip]
